// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using OLB.Web.Models;
using System;

namespace OLB.Web.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OLB.Web.Models.Application", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApplicationType");

                    b.Property<DateTimeOffset>("ExpirationDate");

                    b.Property<DateTimeOffset>("SentAtDate");

                    b.Property<Guid>("SentById");

                    b.Property<string>("SentToEmailAddress");

                    b.Property<DateTimeOffset>("SubmissionDate");

                    b.Property<Guid>("Token");

                    b.HasKey("ApplicationId");

                    b.ToTable("Application");
                });
#pragma warning restore 612, 618
        }
    }
}
